language: java
sudo: required
services:
- docker
after_success:
  - docker build -t "$DOCKER_USERNAME"/backend:travis-$TRAVIS_BUILD_NUMBER .
  - if [ "$TRAVIS_BRANCH" == "master" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin; docker push "$DOCKER_ID"/backend:travis-$TRAVIS_BUILD_NUMBER; fi
notifications:
  email: true
  