language: java
sudo: required
services:
- docker
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then  docker build -t "$DOCKER_ID"/backend:travis-$TRAVIS_BUILD_NUMBER . ; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then  docker build -t "$DOCKER_ID"/backend:latest . ; fi
- if [ "$TRAVIS_BRANCH" != "master" ]; then  docker build -t "$DOCKER_ID"/backend:dev . ; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin; docker push "$DOCKER_ID"/backend:travis-$TRAVIS_BUILD_NUMBER; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin; docker push "$DOCKER_ID"/backend:latest; fi
- if [ "$TRAVIS_BRANCH" != "master" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin; docker push "$DOCKER_ID"/backend:dev; fi