language: java
sudo: required
services:
- docker
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
    region: us-east-2
    app: backend
    env: Backend-env
  bucket_name: elasticbeanstalk-us-east-2-050799799876
  bucket_path: backend