version: '3'
services:
  mongo:
    image: mongo
    restart: on-failure
    ports:
    - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 4001:8081
  mongoclient:
    image: mongoclient/mongoclient
    restart: 'no'
    ports:
    - 4000:3000
    environment:
      MONGO_URL: mongodb://mongo:27017/mydb
      MONGOCLIENT_DEFAULT_CONNECTION_URL: mongodb://mongo:27017/mydb
  backend:
    image: feb18/backend:latest-dev
    restart: 'no'
    ports:
    - 8080:8080