version: '3'
services:
  mongo:
    image: mongo
    restart: on-failure
    ports:
    - 27017:27017
  mongoclient:
    image: mongoclient/mongoclient
    restart: 'no'
    ports:
    - 4000:3000
    environment:
      MONGO_URL: mongodb://mongo:27017/mydb
      MONGOCLIENT_DEFAULT_CONNECTION_URL: mongodb://mongo:27017/mydb
