apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
      - name: backend
        image: feb18/backend:travis-40
        ports:
        - containerPort: 8080
        env:
        - name: spring_data_mongodb_database
          value: ipsc_db
        - name: spring_data_mongodb_host
          value: mongo-service
        - name: spring_data_mongodb_port
          value: '27017'