apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
      - name: backend
        image: feb18/backend
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_DATABASE
          value: ipsc_db
        - name: MONGODB_PORT
          value: 27017
        - name: MONGODB_HOST
          value: mongo-service