apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport
spec:
  type: NodePort
  selector:
    component: backend
  ports:
  - name: backend
    port: 8080
    targetPort: 8080
    nodePort: 31080