apiVersion: v1
kind: Service
metadata:
  name: mongo-nodeport
spec:
  type: NodePort
  selector:
    component: mongo
    environment: dev
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 31017