apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-gui-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: mongogui
  template:
    metadata:
      labels:
        component: mongogui
    spec:
      containers:
      - name: mongoclient
        image: mongoclient/mongoclient
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: mongodb://mongo-service:27017/mydb
        - name: MONGOCLIENT_DEFAULT_CONNECTION_URL
          value: mongodb://mongo-service:27017/mydb