CREATE TABLE PAGEADMIN
(
   ID SERIAL,
   NAME VARCHAR (50) NOT NULL UNIQUE,
   DESCRIPTION VARCHAR (200)
);
CREATE TABLE COUNTRIES
(
   ID SERIAL,
   CODE CHAR (3) NOT NULL UNIQUE,
   NAME_EN VARCHAR (50) NOT NULL UNIQUE,
   NAME_DE VARCHAR (50),
   NAME_FR VARCHAR (50)
);
CREATE TABLE SHOOTERS
(
   ID SERIAL,
   USERNAME VARCHAR (20) NOT NULL UNIQUE,
   PASSWORDSTR VARCHAR (50) NOT NULL,
   FIRSTNAME VARCHAR (40) NOT NULL,
   LASTNAME VARCHAR (40) NOT NULL,
   EMAIL VARCHAR (50) NOT NULL,
   COUNTRY_ID NUMERIC NOT NULL,
   IPSC_LICENCE VARCHAR (20)
);
CREATE TABLE COMPETITION_TYPE
(
   ID SERIAL,
   NAME VARCHAR (50) NOT NULL UNIQUE,
   DESCRIPTION VARCHAR (200)
);
CREATE TABLE DEVISION_TYPE
(
   ID SERIAL,
   NAME VARCHAR (50),
   DESCRIPTION VARCHAR (200)
);
CREATE TABLE ADDRESS
(
   ID SERIAL,
   NAME VARCHAR (50),
   street varchar (200),
   country_id numeric,
   city varchar (200)
);
CREATE TABLE STATUS_TYPE
(
   ID SERIAL,
   NAME_EN VARCHAR (50),
   NAME_DE VARCHAR (50),
   NAME_FR VARCHAR (50)
);
CREATE TABLE ORGANISER
(
   ID SERIAL,
   NAME VARCHAR (50),
   address_id numeric
);
CREATE TABLE EVENTLOCATION
(
   ID SERIAL,
   NAME VARCHAR (50),
   description VARCHAR (50),
   address_id numeric,
   notes text
);
CREATE TABLE COMPETITIONS
(
   ID SERIAL,
   COMPETITION_TYPE_ID NUMERIC NOT NULL,
   DEVISION_TYPE_ID NUMERIC NOT NULL,
   COUNTRY_ID NUMERIC NOT NULL,
   DATE_START TIMESTAMP NOT NULL,
   DATE_END TIMESTAMP NOT NULL,
   LEVEL NUMERIC NOT NULL,
   STAGES NUMERIC NOT NULL,
   BULLET_COUNTS NUMERIC,
   organiser_id NUMERIC,
   title varchar (100),
   EVENTLOCATION NUMERIC,
   status_id NUMERIC,
   reg_open timestamp,
   reg_close timestamp,
   auslastung NUMERIC -- should be calculated
);
CREATE TABLE REGISTRATIONS
(
   ID SERIAL,
   COMPETITION_ID NUMERIC NOT NULL,
   SHOOTER_ID NUMERIC NOT NULL,
   REGISTRATION_DATE TIMESTAMP
);
COMMIT;